spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/CashCloud_realm
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-from, gateway-service
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
          filters:
            - AddResponseHeader=X-Response-generated-by, gateway
  application:
    name: gateway-service
server:
  port: 9090

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:9090/actuator/info
    healthCheckUrlPath: http://localhost:9090/actuator/health

#actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: info, health
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
info:
  app:
    name: gateway-service
    description: This gateway is responsible for redirecting each request to the corresponding MS
