spring:
  application:
    name: notifications-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 465
    username: cashcloud.noreply@gmail.com
    password: glni eqzx tosu mnkj
    # TLS/SSL
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
          ssl:
            enable: true
            
server:
  port: 8082
  
eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8082/actuator/info
    healthCheckUrlPath: http://localhost:8082/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
info:
  app:
    name: notifications-service
    description: This microservice is responsible for responding to each use case that needs to be notified.
